### ISSUE TITLE
"invalid channel 3" with multiple client events

### ISSUE THREAD

**Issue by Luminoth** [projectharmonia/bevy_replicon_renet#10]
Hi, I'm working on a project (https://github.com/luminoth/bevy-multiplayer) that's using `bevy_replicon_renet` and I'm having an issue when adding a second client event (with `add_client_event`). It seems like as soon as I just add it, I get this error on my server:

```
thread 'Compute Task Pool (6)' panicked at /home/shane/.cargo/registry/src/index.crates.io-6f17d22bba15001f/renet-0.0.16/src/remote_connection.rs:349:13:
Called 'receive_message' with invalid channel 3
```

I haven't seen any issues like this raised in `bevy_replicon`, `renet` or `bevy_replicon_renet` and so I'm not really sure what I'm doing wrong here or why it's breaking. I haven't seen either any examples of supporting more than one event, so is it just that you can't do that? Sorry that's not a lot of detail, I'm very confused myself so I guess whatever else I can provide here, please let me know.

**Comment by Shatur** [comment]
> I haven't seen either any examples of supporting more than one event, so is it just that you can't do that?

Should work just fine.

> Called 'receive_message' with invalid channel 3

Looks like there is no channel with id 3. By any chance you registered different events on client and server? `add_client_event` should be called on **both** client and server.
Could you also provide logs? Run both apps with `RUST_LOG=bevy_replicon=debug cargo run ..`.

**Comment by Luminoth** [comment]
It should be the same events on both, they're getting registered in a shared library. Here's the full logs from the server:

```
initializing server ...
2024-11-04T19:17:41.127376Z DEBUG bevy_replicon::core::event_registry::client_event: registering client event `game::network::MoveInputEvent`
2024-11-04T19:17:41.127398Z DEBUG bevy_replicon::core::channels: creating a client channel with ID 2
2024-11-04T19:17:41.127404Z DEBUG bevy_replicon::core::event_registry::client_event: registering client event `game::network::PlayerJumpEvent`
2024-11-04T19:17:41.127410Z DEBUG bevy_replicon::core::channels: creating a client channel with ID 3
2024-11-04T19:17:41.128867Z DEBUG bevy_replicon::core::replicon_server: changing `RepliconServer` running status to `true`
2024-11-04T19:17:57.580318Z DEBUG bevy_replicon::core::connected_clients: adding connected `ClientId(1730747877551)`
2024-11-04T19:17:57.580362Z DEBUG bevy_replicon::core::replicated_clients: starting replication for `ClientId(1730747877551)`
thread 'Compute Task Pool (5)' panicked at /home/shane/.cargo/registry/src/index.crates.io-6f17d22bba15001f/renet-0.0.16/src/remote_connection.rs:349:13:
Called 'receive_message' with invalid channel 3
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_replicon_renet::server::RepliconRenetServerPlugin::receive_packets`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
```

and the full logs from the client:

```
initializing client ...
2024-11-04T19:17:52.732350Z DEBUG bevy_replicon::core::event_registry::client_event: registering client event `game::network::MoveInputEvent`
2024-11-04T19:17:52.732371Z DEBUG bevy_replicon::core::channels: creating a client channel with ID 2
2024-11-04T19:17:52.732378Z DEBUG bevy_replicon::core::event_registry::client_event: registering client event `game::network::PlayerJumpEvent`
2024-11-04T19:17:52.732383Z DEBUG bevy_replicon::core::channels: creating a client channel with ID 3
2024-11-04T19:17:52.771322Z DEBUG bevy_replicon::core::replicon_client: changing `RepliconClient` status to `Connecting`
2024-11-04T19:17:57.589867Z DEBUG bevy_replicon::core::replicon_client: changing `RepliconClient` status to `Connected { client_id: Some(ClientId(1730747877551)) }`
```

It sure looks like its setting up the channels correctly, the events match on both. The `PlayerJumpEvent` is the event I'm adding and its definition looks like this:

```
#[derive(Debug, Event, Serialize, Deserialize)]
pub struct PlayerJumpEvent;
```

That's in the shared library so it should be the same on both ends.

**Comment by Shatur** [comment]
Yes, this looks correct!
Let's see if channels are created on the backend (`bevy_replicon_renet` in your case) side. Could you run with `RUST_LOG=bevy_replicon_renet cargo run ..`?

I tried reproducing it on the `simple_box` example, but no luck. Here is my diff:
```patch
diff --git a/examples/simple_box.rs b/examples/simple_box.rs
index 2fc68b6..c5699d5 100644
--- a/examples/simple_box.rs
+++ b/examples/simple_box.rs
@@ -50,6 +50,7 @@ impl Plugin for SimpleBoxPlugin {
         app.replicate::<PlayerPosition>()
             .replicate::<PlayerColor>()
             .add_client_event::<MoveDirection>(ChannelKind::Ordered)
+            .add_client_event::<TestEvent>(ChannelKind::Unordered)
             .add_systems(
                 Startup,
                 (Self::read_cli.map(Result::unwrap), Self::spawn_camera),
@@ -195,7 +196,12 @@ impl SimpleBoxPlugin {
     }
 
     /// Reads player inputs and sends [`MoveDirection`] events.
-    fn read_input(mut move_events: EventWriter<MoveDirection>, input: Res<ButtonInput<KeyCode>>) {
+    fn read_input(
+        mut move_events: EventWriter<MoveDirection>,
+        mut test_events: EventWriter<TestEvent>,
+        input: Res<ButtonInput<KeyCode>>,
+    ) {
+        test_events.send(TestEvent);
         let mut direction = Vec2::ZERO;
         if input.pressed(KeyCode::ArrowRight) {
             direction.x += 1.0;
@@ -292,3 +298,6 @@ struct PlayerColor(Color);
 /// A movement event for the controlled box.
 #[derive(Debug, Default, Deserialize, Event, Serialize)]
 struct MoveDirection(Vec2);
+
+#[derive(Debug, Deserialize, Event, Serialize, Clone)]
+struct TestEvent;
```

**Comment by Luminoth** [comment]
Hm, that didn't actually produce any logs. I'm guessing that's not expected?

I don't know how much it would help to see but these are the relevant Cargo.toml's:

[shared lib](https://github.com/Luminoth/bevy-multiplayer/blob/main/game/Cargo.toml)
[client](https://github.com/Luminoth/bevy-multiplayer/blob/main/client/Cargo.toml)
[server](https://github.com/Luminoth/bevy-multiplayer/blob/main/server/Cargo.toml)

is it possible I goofed up the dependencies in one of those? I'll mess around with that example a bit and see if I can't get it to break.

**Comment by Shatur** [comment]
> Hm, that didn't actually produce any logs. I'm guessing that's not expected?

Yes, I would expect to see `creating channel config ...` for each channel :thinking: 

> is it possible I goofed up the dependencies in one of those?

This also looks correct. Except maybe I would remove default dependencies for `shared lib` (I assume that you link the shared lib to both client and server). But it's unrelated to the issue.

I would assume that something is wrong with the way you create `RenetClient` and `RenetServer`. Double check [this](https://docs.rs/bevy_replicon_renet/latest/bevy_replicon_renet/#server-and-client-creation) part, you probably forgot to pass channels to the connection.

**Comment by Luminoth** [comment]
Ooof, yep, that was it. I think that was in my mental list to come back to (I was just using `ConnectionConfig::default()`) and I must've just forgot. Thanks for the help working through that.

While I'm here real quick, would it make sense to add conversion between [bevy_replicon ClientId](https://docs.rs/bevy_replicon/latest/bevy_replicon/core/struct.ClientId.html) and [renet ClientId](https://docs.rs/renet/latest/renet/struct.ClientId.html), and `impl Display` for the `replicon` `ClientId` ? It seems like the raw clientId is the same for both types, but being distinct types I've run into a couple situations where I need to convert between them.

**Comment by Shatur** [comment]
> I think that was in my mental list to come back to (I was just using ConnectionConfig::default())

You are not alone 😅 Renet's default is to create 3 channels of each type, this is why it works for a single event (replicon reserves 2 channels for replication). I think it's weird default, I remember mentioned it to the author in Discord, but he could forgot. Could you open in issue at https://github.com/lucaspoffo/renet ? Just ask to remove the `Default` impl, it's very confusing.

> While I'm here real quick, would it make sense to add conversion between [bevy_replicon ClientId](https://docs.rs/bevy_replicon/latest/bevy_replicon/core/struct.ClientId.html) and [renet ClientId](https://docs.rs/renet/latest/renet/struct.ClientId.html),

Makes sense! It could also be used in the crate, since I also do the mapping. Could you open a PR?

Looks like the issue itself can be closed.

**Comment by UkoeHB** [comment]
Fixed in `renet2`: https://github.com/UkoeHB/renet2/commit/3c39d72ba54a3311aa603ecf0a3e497c3928fb1b

**Comment by Luminoth** [comment]
Alright https://github.com/projectharmonia/bevy_replicon/pull/344 for the `impl Display` and https://github.com/projectharmonia/bevy_replicon_renet/pull/11 for the `ClientId` conversion helpers.
